name: m_login_sdk
description: Flutter-native SDK to simply access the M-Login identity- and user-data system.
repository: https://github.com/SWM-IT/m-login-flutter
issue_tracker: https://github.com/SWM-IT/m-login-flutter/issues
homepage: https://login.muenchen.de
version: 0.7.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

  # Needed to create PKCE challenges and verification codes
  crypto: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: de.swm.m_login_sdk
        pluginClass: MLoginSdkPlugin
      ios:
        pluginClass: MLoginSdkPlugin

  assets:
    - lib/assets/
