name: m_login_sdk
description: Flutter-native SDK to simply access the M-Login identity- and user-data system.
repository: https://github.com/SWM-IT/m-login-flutter
issue_tracker: https://github.com/SWM-IT/m-login-flutter/issues
homepage: https://login.muenchen.de
version: 0.2.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Handles launching and closing secure browser contexts
  flutter_web_auth: ^0.4.0

  # Needed to create PKCE challenges and verification codes
  crypto: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 1.0.4

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
