include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
